### ISSUE TITLE
Fixed compatibility with struct

### ISSUE THREAD

**Issue by hgrecco** [hgrecco/pyvisa-py#35]
See https://github.com/hgrecco/pyvisa/issues/149

**Comment by hgrecco** [comment]
This might be fixed in the latest pyvisa (from pypi) and pyvisa-py (from github) Can you update both?

**Comment by enzo96** [comment]
Hi, 

I found a solution which solves the problem. I installed python-ivi and its extension python-vxi11, which allows to control instruments over Ethernet. Now I can very simply communicate with my Analyzer. Thank you for your help, 
Bye

**Comment by hgrecco** [comment]
Lets port that solution to pyvisa-py

**Comment by hgrecco** [comment]
Fixed with #31

**Comment by twitst12** [comment]
Hi enzo96
I'm working on the same project that you. Have you been able to automate the antenna rotator in order to make radiance diagrams measurments using the raspberry pi ? Because I have some issues related with NI-VISA. And my problem is that I can't install it on raspberry. 
what have you done to install it ?
